trigger:
  - master
  - refs/tags/*

variables:
  - name: CI
    value: true
  - group: pypi-credentials

jobs:
  - job: test
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: 3.8
      - bash: scripts/install
        displayName: "Install dependencies"
      - bash: scripts/test
        displayName: "Test"

  - job: pypi
    dependsOn: [test]
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: 3.8
      - bash: scripts/install
        displayName: "Install dependencies"
      - bash: scripts/build
        displayName: "Build package"
      - bash: scripts/publish
        env:
          GIT_REF: $(Build.SourceBranch)
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: $(pypiTestToken)
          TWINE_REPOSITORY: testpypi
        displayName: "Publish package"
